language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: BWp3jZ1od6Ux12Jdqzxf3xH3epzI37fJr9dOgnLuYc0ZWknK1yO/0B7POK2YWdGGMGOo2cfhlN7neMj+PnRgF3dp/LH3GpCIL7F+bNDKtpvVjkExvzCUoKs/hISyDhzgyuxxkzybb9zZXXhT2O0hzbmykA70Kf9kqguNwWJSkv+x1ZLxEIrPep/jY3oAWoZoYf2U7et/dhR3974bqbbEuiF4XGd0H3ropTDILsPqu2KCEp9BF6o5QfBDMuzJyJtb8rT+MvaokXplXoEYDsZgsC0lxa2gCaOsfytJRPQL818kjxrvtjWEHwxfd2YJ0btrn/MxDDy8irDf2AIpYbqzcNHG8m072RF5jmhvDMp6vncbqcg0hDT9BEJaRffCBsMtuTP3hGw64iIS2vrYaIIz+BLrIBOmPGjnKzY5bhxK6/9GklfQqBatC016SzFkgfIDjmI5zM4TxtFFqYUvJGaKTnPy2mfWsZT5/J+aGUbclonsN27Xx3li2du8+Gu0k9d/r+mrC55KWP4vWQTSuR1OqKY5v5KjKCgECCyhVa5OEAPvOfoFlTo9l4d3CN6k2060u3QHzkcEJTugwqMbGACxuUkpnhNoZ2QWB7Dp+x0ZQQTrNR+laPDMCQIi02j7zfTGwGTto6NfS62Op1bSQUYkWItVlgaIRRH78xrpi9vG11s=
  app: hidden-ridge-15509
  on:
    repo: qxj1210/projet
